services:
  crocus:
    build:
      context: ./
      network: host
    environment:
      - "CROCUS__APIS__ICANHAZDADJOKE__HOST=${CROCUS__APIS__ICANHAZDADJOKE__HOST:-icanhazdadjoke.com}"
      - "CROCUS__APIS__ICANHAZDADJOKE__PATH=${CROCUS__APIS__ICANHAZDADJOKE__PATH:-}"
      - "CROCUS__APIS__ICANHAZDADJOKE__PORT=${CROCUS__APIS__ICANHAZDADJOKE__PORT:-}"
      - "CROCUS__APIS__ICANHAZDADJOKE__SCHEME=${CROCUS__APIS__ICANHAZDADJOKE__SCHEME:-https}"
      - "CROCUS__APIS__SCORPION__HOST=${CROCUS__APIS__SCORPION__HOST:-localhost}"
      - "CROCUS__APIS__SCORPION__PATH=${CROCUS__APIS__SCORPION__PATH:-}"
      - "CROCUS__APIS__SCORPION__PORT=${CROCUS__APIS__SCORPION__PORT:-20001}"
      - "CROCUS__APIS__SCORPION__SCHEME=${CROCUS__APIS__SCORPION__SCHEME:-http}"
      - "CROCUS__DEBUG=${CROCUS__DEBUG:-true}"
      - "CROCUS__SECRETS__SHARED=${CROCUS__SECRETS__SHARED:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}"
      - "CROCUS__SERVER__HOST=${CROCUS__SERVER__HOST:-0.0.0.0}"
      - "CROCUS__SERVER__PORT=${CROCUS__SERVER__PORT:-20020}"
      - "CROCUS__URLS__CROCUS__HOST=${CROCUS__URLS__CROCUS__HOST:-localhost}"
      - "CROCUS__URLS__CROCUS__PATH=${CROCUS__URLS__CROCUS__PATH:-}"
      - "CROCUS__URLS__CROCUS__PORT=${CROCUS__URLS__CROCUS__PORT:-20020}"
      - "CROCUS__URLS__CROCUS__SCHEME=${CROCUS__URLS__CROCUS__SCHEME:-http}"
      - "CROCUS__URLS__ORCHID__HOST=${CROCUS__URLS__ORCHID__HOST:-localhost}"
      - "CROCUS__URLS__ORCHID__PATH=${CROCUS__URLS__ORCHID__PATH:-}"
      - "CROCUS__URLS__ORCHID__PORT=${CROCUS__URLS__ORCHID__PORT:-20120}"
      - "CROCUS__URLS__ORCHID__SCHEME=${CROCUS__URLS__ORCHID__SCHEME:-http}"
    network_mode: host
